# Generated by Django 3.2.7 on 2021-11-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aditionalimage_bb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='contacts',
            field=models.TextField(max_length=100, verbose_name='Контакты'),
        ),
        migrations.DeleteModel(
            name='AditionalImage',
        ),
    ]
