# Generated by Django 3.2.7 on 2021-11-09 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211109_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subrubric',
            options={'ordering': ('super_rubric__order', 'super_rubric__name', 'order', 'name'), 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterModelOptions(
            name='superrubric',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.RemoveField(
            model_name='bb',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='price',
        ),
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.subrubric', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.TextField(max_length=40, verbose_name='Название темы'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='super_rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.superrubric', verbose_name='Тема'),
        ),
    ]
