# Generated by Django 3.2.7 on 2021-11-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211116_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answers', models.TextField(blank=True, max_length=50, verbose_name='Ответ')),
                ('answer', models.BooleanField(default=False, verbose_name='Правильный ответ')),
            ],
        ),
        migrations.RemoveField(
            model_name='asks',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='asks',
            name='text_answers',
        ),
    ]
