# Generated by Django 3.2.7 on 2021-11-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211118_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='asks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.asks', verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='asks',
            name='bb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.bb', verbose_name='Заголовок вопроса'),
        ),
    ]
