# Generated by Django 3.2.7 on 2021-11-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211118_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='asks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.bb', verbose_name='Ответы'),
        ),
    ]
