# Generated by Django 3.2.7 on 2021-11-19 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_answers_asks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='asks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.asks', verbose_name='Ответы'),
        ),
    ]
