# Generated by Django 3.2.7 on 2021-11-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_asks_bb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='asks',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='text_answers',
        ),
        migrations.AddField(
            model_name='answers',
            name='header',
            field=models.CharField(default='Вопрос', max_length=200, verbose_name='Заголовок вопроса'),
        ),
        migrations.AddField(
            model_name='answers',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.bb', verbose_name='Вопросы'),
        ),
        migrations.AddField(
            model_name='answers',
            name='text_answers_1',
            field=models.TextField(blank=True, db_index=True, max_length=50, verbose_name='Ответ-1'),
        ),
        migrations.AddField(
            model_name='answers',
            name='text_answers_2',
            field=models.TextField(blank=True, db_index=True, max_length=50, verbose_name='Ответ-2'),
        ),
        migrations.AddField(
            model_name='answers',
            name='text_answers_3',
            field=models.TextField(blank=True, db_index=True, max_length=50, verbose_name='Ответ-3'),
        ),
        migrations.AddField(
            model_name='answers',
            name='text_answers_4',
            field=models.TextField(blank=True, db_index=True, max_length=50, verbose_name='Ответ-4'),
        ),
        migrations.DeleteModel(
            name='Asks',
        ),
    ]
