# Generated by Django 3.2.7 on 2021-11-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211123_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='header_1',
            field=models.TextField(blank=True, default='Вопрос', max_length=200, verbose_name='Заголовок вопроса'),
        ),
        migrations.AddField(
            model_name='bb',
            name='header_2',
            field=models.TextField(blank=True, default='Вопрос', max_length=200, verbose_name='Заголовок вопроса'),
        ),
        migrations.AddField(
            model_name='bb',
            name='header_3',
            field=models.TextField(blank=True, default='Вопрос', max_length=200, verbose_name='Заголовок вопроса'),
        ),
        migrations.AddField(
            model_name='bb',
            name='header_4',
            field=models.TextField(blank=True, default='Вопрос', max_length=200, verbose_name='Заголовок вопроса'),
        ),
        migrations.AddField(
            model_name='bb',
            name='header_5',
            field=models.TextField(blank=True, default='Вопрос', max_length=200, verbose_name='Заголовок вопроса'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-4'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers_1',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-1'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers_10',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-2'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers_11',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-3'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers_12',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-4'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers_13',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-1'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers_14',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-2'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers_15',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-3'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers_16',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-4'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers_2',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-2'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers_3',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-3'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers_4',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-4'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers_5',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-1'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers_6',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-2'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers_7',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-3'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers_8',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-4'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers_9',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-1'),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
