# Generated by Django 3.2.7 on 2021-11-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211130_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bb',
            old_name='text_answers',
            new_name='text_answers4',
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers1',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-1'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers2',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-2'),
        ),
        migrations.AddField(
            model_name='bb',
            name='text_answers3',
            field=models.CharField(blank=True, db_index=True, max_length=70, verbose_name='Ответ-3'),
        ),
    ]
