# Generated by Django 3.2.7 on 2022-01-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_advuser_send_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bb',
            old_name='text_answers4',
            new_name='answers_1',
        ),
        migrations.RenameField(
            model_name='bb',
            old_name='text_answers_12',
            new_name='answers_2',
        ),
        migrations.RenameField(
            model_name='bb',
            old_name='text_answers_16',
            new_name='answers_3',
        ),
        migrations.RenameField(
            model_name='bb',
            old_name='text_answers_4',
            new_name='answers_4',
        ),
        migrations.RenameField(
            model_name='bb',
            old_name='text_answers_8',
            new_name='answers_5',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='header_1',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='header_2',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='header_3',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='header_4',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='header_5',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='text_answers1',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='text_answers2',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='text_answers3',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='text_answers_1',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='text_answers_10',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='text_answers_11',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='text_answers_13',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='text_answers_14',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='text_answers_15',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='text_answers_2',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='text_answers_3',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='text_answers_5',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='text_answers_6',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='text_answers_7',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='text_answers_9',
        ),
    ]
