# Generated by Django 3.2.7 on 2022-01-13 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220111_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='answers_1',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='answers_10',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='answers_2',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='answers_3',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='answers_4',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='answers_5',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='answers_6',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='answers_7',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='answers_8',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='answers_9',
        ),
        migrations.CreateModel(
            name='TestBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_test_1', models.TextField(max_length=200, verbose_name='Текст вопроса')),
                ('answers_1', models.IntegerField(db_index=True, max_length=70, verbose_name='Ответ-1')),
                ('ask_test_2', models.TextField(max_length=200, verbose_name='Текст вопроса')),
                ('answers_2', models.IntegerField(db_index=True, max_length=70, verbose_name='Ответ-2')),
                ('ask_test_3', models.TextField(max_length=200, verbose_name='Текст вопроса')),
                ('answers_3', models.IntegerField(db_index=True, max_length=70, verbose_name='Ответ-3')),
                ('ask_test_4', models.TextField(max_length=200, verbose_name='Текст вопроса')),
                ('answers_4', models.IntegerField(db_index=True, max_length=70, verbose_name='Ответ-4')),
                ('ask_test_5', models.TextField(max_length=200, verbose_name='Текст вопроса')),
                ('answers_5', models.IntegerField(db_index=True, max_length=70, verbose_name='Ответ-5')),
                ('ask_test_6', models.TextField(max_length=200, verbose_name='Текст вопроса')),
                ('answers_6', models.IntegerField(db_index=True, max_length=70, verbose_name='Ответ-6')),
                ('ask_test_7', models.TextField(max_length=200, verbose_name='Текст вопроса')),
                ('answers_7', models.IntegerField(db_index=True, max_length=70, verbose_name='Ответ-7')),
                ('ask_test_8', models.TextField(max_length=200, verbose_name='Текст вопроса')),
                ('answers_8', models.IntegerField(db_index=True, max_length=70, verbose_name='Ответ-8')),
                ('ask_test_9', models.TextField(max_length=200, verbose_name='Текст вопроса')),
                ('answers_9', models.IntegerField(db_index=True, max_length=70, verbose_name='Ответ-9')),
                ('ask_test_10', models.TextField(max_length=200, verbose_name='Текст вопроса')),
                ('answers_10', models.IntegerField(db_index=True, max_length=70, verbose_name='Ответ-10')),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.bb', verbose_name='Тест')),
            ],
        ),
    ]
